// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project-GPS

#include "../ui.h"

void ui_ScreenIQ_screen_init(void)
{
    ui_ScreenIQ = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenIQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ScreenIQ);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -134);
    lv_obj_set_y(ui_Label3, -108);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "IQ plot");

    lv_obj_add_event_cb(ui_ScreenIQ, ui_event_ScreenIQ, LV_EVENT_ALL, NULL);

}
