// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project-GPS

#include "../ui.h"

void ui_ScreenPosition_screen_init(void)
{
    ui_ScreenPosition = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPosition, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_ScreenPosition);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -128);
    lv_obj_set_y(ui_Label4, -108);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Position");

    lv_obj_add_event_cb(ui_ScreenPosition, ui_event_ScreenPosition, LV_EVENT_ALL, NULL);

}
