// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project-GPS

#ifndef _SQUARELINE_PROJECT_GPS_UI_H
#define _SQUARELINE_PROJECT_GPS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenConfigure
void ui_ScreenConfigure_screen_init(void);
void ui_event_ScreenConfigure(lv_event_t * e);
extern lv_obj_t * ui_ScreenConfigure;
extern lv_obj_t * ui_Label1;
void ui_event_btnStartStop(lv_event_t * e);
extern lv_obj_t * ui_btnStartStop;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_PanelConfigureSats;
void ui_event_TextAreaPRN1(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPRN1;
void ui_event_TextAreaPRN2(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPRN2;
void ui_event_TextAreaPRN3(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPRN3;
void ui_event_TextAreaPRN4(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPRN4;
extern lv_obj_t * ui_Label5;
void ui_event_TextAreaFreq1(lv_event_t * e);
extern lv_obj_t * ui_TextAreaFreq1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
void ui_event_TextAreaFreq2(lv_event_t * e);
extern lv_obj_t * ui_TextAreaFreq2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label10;
void ui_event_TextAreaFreq3(lv_event_t * e);
extern lv_obj_t * ui_TextAreaFreq3;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
void ui_event_TextAreaFreq4(lv_event_t * e);
extern lv_obj_t * ui_TextAreaFreq4;
extern lv_obj_t * ui_Label13;
void ui_event_btnStop(lv_event_t * e);
extern lv_obj_t * ui_btnStop;
extern lv_obj_t * ui_Label14;
void ui_event_btnRestartAcq(lv_event_t * e);
extern lv_obj_t * ui_btnRestartAcq;
extern lv_obj_t * ui_Label15;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// SCREEN: ui_ScreenState
void ui_ScreenState_screen_init(void);
void ui_event_ScreenState(lv_event_t * e);
extern lv_obj_t * ui_ScreenState;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_lblStateCommon;
extern lv_obj_t * ui_lblSysTime1;
// SCREEN: ui_ScreenIQ
void ui_ScreenIQ_screen_init(void);
void ui_event_ScreenIQ(lv_event_t * e);
extern lv_obj_t * ui_ScreenIQ;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Chart1;
// SCREEN: ui_ScreenPosition
void ui_ScreenPosition_screen_init(void);
void ui_event_ScreenPosition(lv_event_t * e);
extern lv_obj_t * ui_ScreenPosition;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_ChartPos;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
