// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project-GPS

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btnStartStopPressed(lv_event_t * e);
void funcShowKeyboard(lv_event_t * e);
void btnStopClick(lv_event_t * e);
void btnCodeSearchClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
